### ISSUE TITLE
V2- Refactor API Guide: QE checklist

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-backup#94]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [ ] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [ ] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by catlook** [comment]
Everything is good except conf.py.  lines 15-16 don't match 15-23 of common.
the space after # in comment lines is missing
blank line before extension missing.
stopping there...i suspect most changes are missing.

**Comment by cyrichardson** [comment]
@catlook Thanks a ton! I will fix conf.py!

**Comment by catlook** [comment]
it does build locally without errors...but because conf.py isn't updated, the doc doesn't look right, unless you build singlehtml

**Comment by catlook** [comment]
hmm nexus build looks good and the git repo shows the conf.py changes.  I'm assuming this is something on my end and blessing this!

**Comment by cyrichardson** [comment]
Yep. conf.py looks ok to me.
